### ISSUE TITLE
Use latest graalvm version and generate a native image

### ISSUE THREAD

**Issue by tonivade** [tonivade/pure-todo-backend#2]
Use graalvm 21.1 version that has support for java 16 to generate a native image

**Comment by tonivade** [comment]
It doesn't work

```
/usr/bin/ld: todo-backend.o: warning: relocation in read-only section `.svm_heap'
/usr/bin/ld: todo-backend.o:(.data+0x8): referencia a `Java_jdk_internal_misc_Unsafe_writeback0' sin definir
/usr/bin/ld: todo-backend.o:(.data+0x608): referencia a `Java_jdk_internal_misc_Unsafe_writebackPostSync0' sin definir
/usr/bin/ld: todo-backend.o:(.data+0xa50): referencia a `Java_jdk_internal_misc_Unsafe_writebackPreSync0' sin definir
/usr/bin/ld: warning: creating DT_TEXTREL in a PIE
collect2: error: ld devolvió el estado de salida 1
```

**Comment by tonivade** [comment]
with latest development version of graal, the native image is generated, but it doesn't work:

```
Exception in thread "main" com.zaxxer.hikari.pool.HikariPool$PoolInitializationException: Failed to initialize pool: null
	at com.zaxxer.hikari.pool.HikariPool.throwPoolInitializationException(HikariPool.java:596)
	at com.zaxxer.hikari.pool.HikariPool.checkFailFast(HikariPool.java:582)
	at com.zaxxer.hikari.pool.HikariPool.<init>(HikariPool.java:115)
	at com.zaxxer.hikari.HikariDataSource.<init>(HikariDataSource.java:81)
	at com.github.tonivade.todo.Application.createDataSource(Application.java:88)
	at com.github.tonivade.todo.Application.buildService(Application.java:52)
	at com.github.tonivade.todo.Application.main(Application.java:36)
Caused by: java.lang.NullPointerException
	at com.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:364)
	at com.zaxxer.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:206)
	at com.zaxxer.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:476)
	at com.zaxxer.hikari.pool.HikariPool.checkFailFast(HikariPool.java:561)
	... 5 more
```

**Comment by tonivade** [comment]
I think the error is related to the h2 jdbc driver

**Comment by tonivade** [comment]
pool problem solved, but I have other problems with reflection and json adapters:

```
Thu Apr 29 14:09:21 CEST 2021
GET /
Accept-encoding:gzip, deflate
Accept:*/*
Connection:keep-alive
Host:localhost:8081
User-agent:HTTPie/1.0.3


Exception in thread "pool-1-thread-4" java.lang.AssertionError
	at com.github.tonivade.purejson.Record.getRecordComponents(Record.java:79)
	at com.github.tonivade.purejson.JsonEncoder.recordEncoder(JsonEncoder.java:84)
	at com.github.tonivade.purejson.JsonEncoder.create(JsonEncoder.java:209)
	at com.github.tonivade.purejson.JsonEncoder.create(JsonEncoder.java:132)
	at com.github.tonivade.purejson.JsonEncoder.lambda$encoder$2(JsonEncoder.java:43)
	at com.github.tonivade.purefun.Producer.get(Producer.java:22)
	at com.github.tonivade.purefun.type.Option.fold(Option.java:163)
	at com.github.tonivade.purefun.type.Option.getOrElse(Option.java:142)
	at com.github.tonivade.purejson.JsonEncoder.encoder(JsonEncoder.java:43)
	at com.github.tonivade.purejson.JsonEncoder.create(JsonEncoder.java:159)
	at com.github.tonivade.purejson.JsonEncoder.create(JsonEncoder.java:135)
	at com.github.tonivade.purejson.JsonEncoder.lambda$encoder$2(JsonEncoder.java:43)
```

**Comment by tonivade** [comment]
It works!!
